# Copia a secret.yaml y completa. NO subas secret.yaml a git.
apiVersion: v1
kind: Secret
metadata:
  name: dr-demo-db
type: Opaque
stringData:
  DB_HOST: "PRIVATE_IP_O_HOSTNAME_DEL_MYSQL"
  DB_USER: "admin"
  DB_PASS: "CambiaEsteP4ssw0rd!"
